### ISSUE TITLE
RPM Advisories

### ISSUE THREAD

**Issue by stevespringett** [OSSIndex/vulns#11]
I'm not positive, but shouldn't https://ossindex.sonatype.org/component/pkg:rpm/openssl@1.0.1e-4?arch=i686&distro=fedora-18 be flagged for heartbleed?

**Comment by OSSIndex-Admin** [comment]
You are quite correct. There are actually a number of RPMs I am missing vulnerabilities for that I have identified recently. I wrote some code that identified a whole bunch of misses for Linux distributions (RPMs, DEBs), and was planning on kicking it off officially soon; since you wrote I will do it today :)

I expect you should see it in there sometime tomorrow. 

Thanks for the notification and help!

Ken

**Comment by stevespringett** [comment]
Awesome. Thanks Ken. Your team is great. Keep up the good work.

**Comment by ken-duck** [comment]
I was taking a look at our results, and noted that the vulnerability is not visible under:

    https://ossindex.sonatype.org/component/pkg:rpm/openssl@1.0.1e-4?arch=i686&distro=fedora-18

but is under

    https://ossindex.sonatype.org/component/pkg:rpm/openssl@1.0.1e?arch=i686&distro=fedora-18

Note the difference is `@1.0.1e-4` vs. `@1.0.1e`

[The CVE](https://nvd.nist.gov/vuln/detail/CVE-2014-0160) does not mention the `-4` portion of these version ranges, and I do not know enough about RedHat versions to know to what that portion of the version refers to. I suspect that it may be a RedHat specific patch or something.

If the CVE had used a version range such as `[1.0.1,1.0.1f],[1.0.1:beta1,1.0.1:beta3]` instead of explicit versions in this case then `1.0.1e-4` would have been implicated, and I *could* override the version manually, however this has to be done on a case-by-case basis at the moment.

Do you have any thoughts on the `-4` part of the version? Can it be removed from your query, since it is not really "supported" by OSS Index at the moment. Otherwise, if I understood what that part of the version meant, we could perhaps strip it from the query on our side, which might make things more clear. Thoughts?

**Comment by stevespringett** [comment]
I had to look it up. RedHat conventions is `name-version-release.architecture`. So, in this specific case, the -4 could safely be stripped off since it's not part of the version. However, by the same logic, the -4 should have never been supplied as part of the purl in the first place.

In fact, I think the purl supplied should have been:
```
pkg:rpm/openssl@1.0.1e?release=4&arch=i686&distro=fedora-18
```

instead of:
```
pkg:rpm/openssl@1.0.1e-4?arch=i686&distro=fedora-18
```

http://ftp.rpm.org/max-rpm/ch-rpm-file-format.html#S1-RPM-FILE-FORMAT-FILE-NAMING-CONVENTION

**Comment by ken-duck** [comment]
Verified in product.
