### ISSUE TITLE
Missing advisory against snakeyaml - CVE-2017-18640

### ISSUE THREAD

**Issue by talios** [OSSIndex/vulns#118]
**Advisory details**
```
  URL: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18640
  format: maven
  namespace: org.yaml
  name: snakeyaml
  versions: 1.25
```

**More information**

This CVE was raised December 2019. How often does oss-index synchronise with the public Mitre/CVE databases?

**Comment by ken-duck** [comment]
In this case OSS Index already had the CVE in our database, however the CPE code was not associated with the maven project yet. This is often a manual process unless certain conditions are met, in order to ensure we do not get lots and lots of false positives. Our researchers did not notice this one come in, so it had not yet been added. Thanks to your help, the vulnerability should show up sometime tomorrow.

Incidentally, we are working on a brand new research process with new tooling which will greatly reduce the number of CPE/CVE misses. This is a major project, but we are hoping for completion sometime early next year.

**Comment by ndonewar** [comment]
Closing this issue as it appears to be resolved. Please feel free to reopen or create a new issue if needed. Thanks!
