### ISSUE TITLE
Missing advisory: CVE-2020-17530 for pkg:maven/org.apache.struts/struts2-core

### ISSUE THREAD

**Issue by nscuro** [OSSIndex/vulns#137]
**Advisory details**
```
  URL: https://cwiki.apache.org/confluence/display/WW/S2-061
  format: maven
  namespace: org.apache.struts
  name: struts2-core
  versions: 2.0.0-2.5.25
```

**More information**
* https://nvd.nist.gov/vuln/detail/CVE-2020-17530
* https://securityboulevard.com/2020/12/contrast-labs-apache-struts-cve-2020-17530/

**Comment by ken-duck** [comment]
It looks like the issue is available on the OSS Index page here: https://ossindex.sonatype.org/component/pkg:maven/org.apache.struts/struts2-core@2.5.25

And it *looks* like the issue has been in the database for a while, so I wonder if there might not be something else wrong. Is there a tool that failed to report this issue?

**Comment by nscuro** [comment]
Thanks for the response, @ken-duck. I checked before opening the issue and I could've sworn it wasn't there at the time. 

And yes, a tool failed to report the vuln, which is how I noticed it was missing in OSSIndex. It reports the vuln now though.
