### ISSUE TITLE
Bug: https://ossindex.sonatype.org/vuln/e27505b2-b0b7-4863-a3f5-8df961db080f

### ISSUE THREAD

**Issue by mattgd** [OSSIndex/vulns#18]
It seems like there's an issue with the version range for this advisory. The [NPM advisory](https://www.npmjs.com/advisories/66) says prior to `2.0.0-alpha8` are vulnerable, while OSSIndex has the range as `(,7.0.0]`.

Thanks!

**Comment by Rmumford52** [comment]
Please let Ken duck know that I'm not confused.   The answer to the problem is json, possibly because of all the emails that ended up in my gmail account.  Tell Ken duck to get json to tell the truth please.   Because I know the website he was on, and it's not good.  I had cybersecurity through Dell confirm the website. 
Rhonda Mumford

**Comment by ken-duck** [comment]
Actually, you have uncovered a deeper problem in our process. This issue *was* originally erroneously added, but the researcher then realized it was a duplicate of another and marked it as such. It seems our pipeline failed to remove the issue from the public database.

So for now I will update the duplicate issue to be correct, but meanwhile we need to debug the pipeline.

Thanks for letting us know.

**Comment by ken-duck** [comment]
The data for npm:mysql appears to be stable, so I am closing this.

However, it is worth noting that in Q1 in this coming year we are doing a fairly dramatic overhaul of the research tools/process which should help prevent problems like this in the future.
