### ISSUE TITLE
CVE-2016-3720 & CVE-2016-7051 do not affect jackson-core

### ISSUE THREAD

**Issue by msymons** [OSSIndex/vulns#195]
**Vulnerability URL**

CVE-2016-3720
```
https://ossindex.sonatype.org/vulnerability/86bfb41b-53e0-4e9f-bda9-73723fb765f1
```
CVE-2016-7051
```
https://ossindex.sonatype.org/vulnerability/5b39de39-3274-4851-bcc4-035c9759bd9f
```

**Description**
Both vulnerabilities are reported by OSS Index as affecting `jackson-dataformat-xml`  (which is correct) but also affecting `jackson-core`  (which is incorrect).

The only affected component should be `jackson-dataformat-xml`

Example:

https://ossindex.sonatype.org/component/pkg:maven/com.fasterxml.jackson.core/jackson-core@2.7.3

Aside: 

When I query the full PURL:

`pkg:maven/com.fasterxml.jackson.core/jackson-core@2.7.3?type=jar`

...only one CVE is reported.  How can this be?

https://ossindex.sonatype.org/component/pkg:maven/com.fasterxml.jackson.core/jackson-core@2.7.3%3Ftype=jar

**Comment by ken-duck** [comment]
This past year among other changes we upgraded the OSS Index vulnerability database. The new database has significantly more vulnerabilities, is much more actively maintained, and has more in depth research on many of the issues. The issue reported here was resolved  in the new database and as such we are closing the issue.

For the record, we are migrating to a new email-based reporting system in order to better mesh with our internal processes, which will allow us to be more reactive to our users.
