### ISSUE TITLE
CVE-2018-1000632: Incorrect Affected Version for dom4j:dom4j

### ISSUE THREAD

**Issue by msymons** [OSSIndex/vulns#196]
**Vulnerability URL**
```
https://ossindex.sonatype.org/vuln/09883ba9-5094-49df-bd4a-1eaf1d6ba07b
```

**Component URL**
```
https://ossindex.sonatype.org/component/pkg:maven/dom4j/dom4j
```

**Description**
The OSS index vulnerability (CVE-2018-1000632) shows incorrect version information when using the dropdown to select Maven `dom4j:dom4j`

![image](https://user-images.githubusercontent.com/4938718/131409251-3af2dd4b-3b25-4bd2-b8b2-d49b10873299.png)

These versions are invalid for this component.  The last version was 1.6.1, which is vulnerable.  From the GitHub advisory:

> Note: This advisory applies to dom4j:dom4j version 1.x legacy artifacts. To resolve this a change to the latest version of org.dom4j:dom4j is recommended.

I am going the guess that this data problem crept in by going a bit too far with fixing #112

**Comment by ken-duck** [comment]
Actually, this is a side effect of how OSS Index manages its vulnerability data. It boils down to this: The OSS Index vulnerability findings do not have knowledge of what versions of a package actually exist, only the vulnerable range. Combined with us grouping like packages together for OSS Index (to allow the research team to discover more new vulnerabilities instead of researching all the package variants) it means that sometimes packages are implicated when they do not have actual version.

Now, as you see we are starting to migrate additional data into the system, including existing package versions, but as yet that data is not merged with the vulnerability information.

Later on in the migration we may be able to start cross referencing the vulnerability ranges with the known versions, and get more precise in our reporting.
