### ISSUE TITLE
Advisory CVE-2012-5783 Missing on Maven commons-httpclient  3.x

### ISSUE THREAD

**Issue by ImmortalUTA** [OSSIndex/vulns#203]
**Advisory details**
```
  URL: https://nvd.nist.gov/vuln/detail/CVE-2012-5783
  format: Maven
  namespace: maven commons-httpclient
  name: commons-httpclient
  versions: 3.x
```

**More information**
OSS Index seems to state on the site that there are 2 severe across different versions. However when you filter by severe vulns, there is only one listed, and it is not this vulnerability. Thank you.

**Comment by ImmortalUTA** [comment]
Small correction here this vuln shows for version 3.0 but it actually effects all versions of 3.x not just 3.0

**Comment by ken-duck** [comment]
You have found an interesting edge case in the way OSS Index works under the covers, but at some point in the (hopefully) not too far future this will be fixed.

Specifically, a variety of packages are grouped together as httpclient; some of those packages are httpclient3 (commons-httpclient), some are httpclient 4. Since they are grouped together in the back end code, vulnerabilities are reported for all version ranges against any httpclient.

However, the web page knows more about versions than the backend vulnerability handling code. It knows that apache commons-httpclient only has versions up to version 3.x, and therefore the table will only report vulnerabilities affecting that version range.

Basically, data on that web page comes from two locations, and therefore they are reporting slightly different things. This won't affect REST API calls or any client tools, because those client tools request vulnerabilities for a specific version (and therefore you will only be presented with the applicable vulnerabilities).

We are in the middle of a rather large data unification effort which will fix this problem. There is no specific end-date as of yet, but rest assured the work is ongoing.

**Comment by ImmortalUTA** [comment]
That is interesting - thank you! I am happy to learn that it doesn't affect
api/client tools though too. Thank you for taking the time to clarify all
of this, much appreciated!

--

Dan Griffin

Web and Mobile Application Security Engineer

GetWellNetwork

m:781.413.6404 | getwellnetwork.com
