### ISSUE TITLE
Missing Ruby vuln in mini_magick

### ISSUE THREAD

**Issue by csansone-handy** [OSSIndex/vulns#21]
Looks like there are 2 vulns in [`mini_magick`](https://ossindex.sonatype.org/component/pkg:gem/mini_magick) that are missing. See: [OSVDB-91231.yml](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/mini_magick/OSVDB-91231.yml) and [CVE-2019-13574.yml](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/mini_magick/CVE-2019-13574.yml)

**Comment by ken-duck** [comment]
Curious. Thanks for the notification. I will get those in today (which means they will show up tomorrow). I will do some debugging on our program too to figure out how they were missed.

**Comment by csansone-handy** [comment]
Thanks Ken! Can you give a high level of what the program is doing to fetch them for those that are curious?

**Comment by ken-duck** [comment]
Generally speaking we clone (or pull) the repository, then look through each *.yml file looking for vulnerabilities we do not already represent. These are passed on to our researchers, whereupon they will do further research (CWE, CVSS scores, etc). Once they are done the issue is published. Publishing happens once (or twice?) a day. It usually takes around a day for issues to find their way through the publishing system (there are a few stages).

OSVDB files are actually ignored at this time due to copyright concerns, but of the two issues you mention one is a CVE, and the OSVDB one actually mentions a CVE (which I did not consider earlier). Because of this I am going to do further research myself to figure out the details and update that one. If there is some way we can further automate those ones I will do so, but that will require talking to legal first :)

The CVE should have found its way in automatically, though.

**Comment by csansone-handy** [comment]
Awesome thanks for the overview!

**Comment by ken-duck** [comment]
Ha. One bit I missed is that when we find a CVE match for a project we also try and look to see whether we can subsequently automatically match additional CVEs (based on CPE codes). This means that once we have one good CVE match (even if we originally missed it), subsequent CVE matches to the same project should be automatically found.

Such is the case here. Now that we matches the CVE you mentioned, further CVEs against this package should show up automatically.

**Comment by ken-duck** [comment]
Some more details:

The OSVDB vulnerability you linked actually represents a CVE, so you should see the CVE show up sometime tomorrow.

The CVE you linked *is* from NVD, but the CVE itself actually has not been completed yet. This is an interesting case, as normally when RubySec mentions a CVE we would just ensure the CVE is linked. However, the CVE does not have complete information yet (it is missing CPE data, for example).

This is a situation that I did not consider: that RubySec has complete information but NVD does not. When the CVE gets its CPEs assigned it will show up automatically, but it would definitely be worth having the vulnerability sooner (as RubySec has provided full details already).

I can add the RubySec issue manually for now, but am going to have to work on a solution that will allow the automatic adding of the RubySec issue when there is a CVE but NVD does not have adequate information yet.

Very interesting case. Thanks!

**Comment by csansone-handy** [comment]
Thanks for the updates Ken. Conceivably you can parse the canonicalized YAML files in the RubySec Vuln DB against the PURLs that you have for each component you have (of type pkg:gem/*). The RubySec Vuln DB's [README.md](https://github.com/rubysec/ruby-advisory-db/blob/master/README.md) gives a good overview of the format of these YAML files

**Comment by ken-duck** [comment]
I verified that both of these are visible now:
