### ISSUE TITLE
Vulnerabilities Found

### ISSUE THREAD

**Issue by MohdRizwan7** [OSSIndex/vulns#211]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL: https://ossindex.sonatype.org/component/pkg:maven/org.jetbrains.kotlin/kotlin-reflect@1.3.72
  format:  maven
  namespace: maven
  name: kotlin-reflect(org.jetbrains.kotlin),kotlin-stdlib-jdk7-1.3.72.jar,kotlin-stdlib-jdk8-1.3.72.jar,kotlin-stdlib-common-1.3.72.jar
  versions:  1.3.72
```

**More information**
These are coming up in our security scans as vulnerable dependency.But in yours its shown as no vulnerabilities.

**Comment by ken-duck** [comment]
The issue with this vulnerability is though it affects Kotlin, deeper research has revealed it does not affect any of the packages that you linked! Currently OSS Index marks "kotlin-relect" as vulnerable, but it is not, so I will be reverting that.

DependencyCheck uses name matching based on the CPE code associated with the vulnerability against the package names, so it will highlight many.

At some point in the not too far future OSS Index's data will be migrated to a new data set which is much more deeply researched and accurate, and it will have precise package names that are vulnerable in this case (as determined by our researchers). Until such a time this vulnerability will be touch-and-go.

**Comment by ken-duck** [comment]
This past year among other changes we upgraded the OSS Index vulnerability database. The new database has significantly more vulnerabilities, is much more actively maintained, and has more in depth research on many of the issues. The more detailed issue matching is now occurring, so the missing vulnerabilities should implicate the "real" vulnerable packages.

For the record, we are migrating to a new email-based reporting system in order to better mesh with our internal processes, which will allow us to be more reactive to our users.
