### ISSUE TITLE
Advisory: Political propaganda in es5-ext

### ISSUE THREAD

**Issue by t-vorobyova** [OSSIndex/vulns#259]
**Advisory details**
```
  URL: [<Advisory URL>](https://github.com/medikoo/es5-ext)
  format: npm
  namespace: pkg:npm/es5-ext
  name: es5-ext
  versions: >0.10.54
```

**More information**
File https://github.com/medikoo/es5-ext/blob/main/_postinstall.js contains code, which outputs message to console

**Comment by ken-duck** [comment]
This past year among other changes we upgraded the OSS Index vulnerability database. The new database has significantly more vulnerabilities, is much more actively maintained, and has more in depth research on many of the issues. The issue reported here *is* reported in the new database and as such we are closing the issue.

For the record, we are migrating to a new email-based reporting system in order to better mesh with our internal processes, which will allow us to be more reactive to our users.
