### ISSUE TITLE
Missing Advisory: CVE-2020-7692 google-oauth-client

### ISSUE THREAD

**Issue by vmvarga** [OSSIndex/vulns#264]
**Advisory details**
```
  URL: https://github.com/googleapis/google-oauth-java-client/issues/469
  format: maven
  namespace: com.google.oauth-client
  name: google-oauth-client
  versions: < 1.31.0
```

**More information**
https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEOAUTHCLIENT-575276

**Comment by ken-duck** [comment]
This past year among other changes we upgraded the OSS Index vulnerability database. The new database has significantly more vulnerabilities, is much more actively maintained, and has more in depth research on many of the issues. The issue reported here *is* reported in the new database and as such we are closing the issue.

For the record, we are migrating to a new email-based reporting system in order to better mesh with our internal processes, which will allow us to be more reactive to our users.
