### ISSUE TITLE
Missing advisory: CVE-2022-0839

### ISSUE THREAD

**Issue by jefffischer** [OSSIndex/vulns#265]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL: https://nvd.nist.gov/vuln/detail/CVE-2022-0839
  format: maven
  namespace: org.liquibase
  name: liquibase-core
  versions: prior to 4.8.0
```

**More information**
Any additional information that might be useful/interesting

**Comment by ken-duck** [comment]
This past year among other changes we upgraded the OSS Index vulnerability database. The new database has significantly more vulnerabilities, is much more actively maintained, and has more in depth research on many of the issues. The issue reported here *is* reported in the new database and as such we are closing the issue.

For the record, we are migrating to a new email-based reporting system in order to better mesh with our internal processes, which will allow us to be more reactive to our users.
