### ISSUE TITLE
Advisory: CVE-2021-32841 

### ISSUE THREAD

**Issue by MichaelThomasMPT** [OSSIndex/vulns#272]
**Advisory details**
```
  URL: https://nvd.nist.gov/vuln/detail/CVE-2021-32841
  format: nuget
  namespace: pkg:nuget/SharpZipLib@1.3.1
  name: SharpZipLib
  versions: 1.3.0<=version<1.3.3
```

**More information**
https://ossindex.sonatype.org/component/pkg:nuget/SharpZipLib@1.3.1

**Comment by ken-duck** [comment]
This past year among other changes we upgraded the OSS Index vulnerability database. The new database has significantly more vulnerabilities, is much more actively maintained, and has more in depth research on many of the issues. The issue reported here *is* reported in the new database and as such we are closing the issue.

For the record, we are migrating to a new email-based reporting system in order to better mesh with our internal processes, which will allow us to be more reactive to our users.
