### ISSUE TITLE
Missing Advisory CVE-2021-34532

### ISSUE THREAD

**Issue by LtheKing** [OSSIndex/vulns#273]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL: https://nvd.nist.gov/vuln/detail/cve-2021-34532
  format: nuget
  namespace: pkg:nuget/Microsoft.AspNetCore.Authentication.JwtBearer@3.1.10
  name: JwtBearer
  versions: 3.1.10
```

**More information**
Any additional information that might be useful/interesting

**Comment by ken-duck** [comment]
This past year among other changes we upgraded the OSS Index vulnerability database. The new database has significantly more vulnerabilities, is much more actively maintained, and has more in depth research on many of the issues. The issue reported here *is* reported in the new database and as such we are closing the issue.

For the record, we are migrating to a new email-based reporting system in order to better mesh with our internal processes, which will allow us to be more reactive to our users.
