### ISSUE TITLE
SLF4JServiceProvider in log4J-SLf4j18-IMPL 2.0 does not implement the getRequestedApiVersion method 

### ISSUE THREAD

**Issue by shine620** [OSSIndex/vulns#292]
SLF4JServiceProvider in log4J-SLf4j18-IMPL 2.0 does not implement the getRequestedApiVersion method , An error occurs when the program starts.

**Comment by ken-duck** [comment]
Sorry for the delay. We have been working on getting appropriate internal processes defined for dealing with data issues in the new data set. We are now working on catching up on the backlog.

What tool are you running that is giving you this error?

**Comment by ken-duck** [comment]
Cleaning up old issues.

For the record, we are migrating to a new email-based reporting system in order to better mesh with our internal processes, which will allow us to be more reactive to our users.

As such, if you notice further issues or would like to follow up on this one, please email [ossindex@sonatype.org](mailto:ossindex@sonatype.org)
