### ISSUE TITLE
API is case sensitive for vulnerability detection while NuGets are not

### ISSUE THREAD

**Issue by PHBourquin** [OSSIndex/vulns#43]
Hello, 

When requesting vulnerabilities for NuGets packages, there is a difference between lower & upper case queries. See for instance :

- https://ossindex.sonatype.org/component/pkg:nuget/Google.Protobuf@3.0.0 (vuln detection working)
- https://ossindex.sonatype.org/component/pkg:nuget/google.protobuf@3.0.0 (vuln detection not working)

Those 2 entries do not lead to the same result regarding vulnerability detection while both seems to point to the same repository https://github.com/google/protobuf.git

Would it be possible to match vulnerability detection with case insensitive queries ?

Thanks a lot

**Comment by ken-duck** [comment]
Sorry for the delay, there have been several unrelated fires that required my attention the past couple of weeks.

Do you know, are *all* nuget packages case insensitive? If so then I am sure I can solve this reasonably quickly.

**Comment by ken-duck** [comment]
Heh, a google search indicates that a LOT of software is having problems with (apparent) nuget gallery's case insensitivity. What makes it even more aggravating is that some alternative NuGet sources *are* case sensitive. Bleagh.

**Comment by ken-duck** [comment]
According to the NuGet v3 API, package names should officially be searched for in lower case:

https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#registration-pages-and-leaves

> ```GET {@id}/{LOWER_ID}/index.json
```
>
> The LOWER_ID value is the desired package ID lowercased using the rules implemented by .NET's System.String.ToLowerInvariant() method.

So I can officially force all nuget package names to lower case which should resolve this problem.

This is apparently a change from the v2 API, but there is no official need for us to be backwards compatible to case sensitive names.

I need to identify the optimal place to make this change still. I need to loop a few folks in. I will endeavour to get a fix in soon.

**Comment by ken-duck** [comment]
Sorry for the delay. I am on the changes now and will hopefully have a good fix shortly.

**Comment by ken-duck** [comment]
Bit of an update. The code has been written, reviewed, and ready for deploy. It required some rework of the database and required some time from a different group, which is why it took a bit of time to get through.

Though it is ready, we do not wish to deploy the change until next week due to holidays and vacations making support a little more difficult to come by if something goes tragically wrong.

**Comment by brittanybelle** [comment]
Hi @PHBourquin , thanks for the bug report!  This bug has been fixed in OSS Index.  You can now see that the following two URIs correctly show the linked vulnerability:

* https://ossindex.sonatype.org/component/pkg:nuget/Google.Protobuf@3.0.0
* https://ossindex.sonatype.org/component/pkg:nuget/google.protobuf@3.0.0

Thanks for using OSS Index, and thanks again for reaching out! Feel free to reach out (you can also email directly to ossindex@sonatype.org) if you have any more questions or concerns.
