### ISSUE TITLE
Missing CVE-2019-16782 for rack Ruby gem

### ISSUE THREAD

**Issue by csansone-handy** [OSSIndex/vulns#56]
**Advisory details**
```
  URL: https://nvd.nist.gov/vuln/detail/CVE-2019-16782
  format: gem
  name: rack
  versions: "< 1.6.12, < 2.0.8"
```

**More information**
It appears that CVE-2019-16782 which affects the `rack` Ruby gem is missing from the OSS Index vulnerabilities. This vulnerability was added to Rubysec on December 18th (9 days ago): See: https://github.com/rubysec/ruby-advisory-db/blob/master/gems/rack/CVE-2019-16782.yml

Can you please get this added to OSS Index?

We saw a similar issue back in August  where some vulnerabilities were not being picked up from Rubysec and auto imported into OSS Index (see #21). Was the team able to track down the issue in the automated feed processor? Should we open a separate bug to track this as it has happened on multiple occasions?

**Comment by ken-duck** [comment]
Ewf. This was resolved some time ago but I missed closing the issue. Make sure the "type/format" you are using is "gem". You can see the vulnerabilities here.

https://ossindex.sonatype.org/component/pkg:gem/Rack

We have a new team to manage the OSS Index service, so we should be seeing more responsiveness in both the research and development sides. For example, it seems that component search in OSS Index uses "rubygems" as the type. This will be resolved very shortly.

Hopefully you find things are working for you. Sorry for the delay and please do let us know if there are problems that you are having.

**Comment by ken-duck** [comment]
Incidentally the issue was added by the researchers without noting the CVE because it was originally identified before we had a CVE (in fact the issue was there when you were looking, it just didn't have the CVE name so was hard to notice). It is this issue: https://ossindex.sonatype.org/vuln/147fc18e-589b-460e-9df7-ccd5903889ce

For clarity I have re-added the issue using the official CVE name. You should see it show up with that name soon.
