### ISSUE TITLE
Incorrect vulnerability details in opencontainers/runc

### ISSUE THREAD

**Issue by adamdecaf** [OSSIndex/vulns#62]
**Vulnerability URL**
Provide the URL to the OSS Index vulnerability. eg:
```
https://ossindex.sonatype.org/vuln/d089f726-f419-4e72-ab60-05be37d02b68
```

**Description**
v1.0.0-rc8 claims to have fixed this CVE 

Source: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc8

**Comment by aeneasr** [comment]
This also applies to v1.0.0 (which has not yet been released) and v1.0.0-rc9! Would be great if this could be resolved!

**Comment by DarthHater** [comment]
@ken-duck haven't looked personally at this, but I'm imagining that @adamdecaf is correct, mind taking a gander?

**Comment by ken-duck** [comment]
It should be fixed on the backend, and hopefully pushed to the public database by sometime tomorrow. This one was interesting; it appears that the CVE feed itself has conflicting information, or there is a mismatch between what NVD thinks it means and what I took their ranges to mean.

Specifically, they do indicate that opencontainers:runc up to **and including** 1.0 are vulnerable. Odd.

Anyhow, it should be fixed in our public data shortly.

**Comment by DarthHater** [comment]
Thanks @ken-duck !!!!

**Comment by ken-duck** [comment]
Working on closing older issues. I just checked, and the data appears to be correct to me.
