### ISSUE TITLE
Advisory: Prototype Pollution

### ISSUE THREAD

**Issue by nikhilgeo** [OSSIndex/vulns#68]
**Advisory details**
```
  URL: https://snyk.io/vuln/SNYK-JS-ANGULAR-534884
  format: npm
  namespace: npm
  name: AngularJS
  versions: before 1.7.9
```

**More information**
Affected versions of this package are vulnerable to Prototype Pollution. The function merge() could be tricked into adding or modifying properties of Object.prototype using a __proto__ payload.

**Comment by ken-duck** [comment]
Oops. Sorry for the delay. I missed seeing this come in. This would be CVE-2019-10768, I expect. I have added that (and another CVE) to angularjs. Any further vulnerabilities assigned to `cpe:2.3:a:angularjs:angular.js` should appear automatically from now on.

The vulnerabilities *should* show up in the public feed sometime today.

Thanks for the pointer. FYI, we are currently doing some restructuring. We will have a research team monitoring this repository soon (instead of myself). This will allow for a much faster response time. Thanks for your patience.

**Comment by nikhilgeo** [comment]
Thank you so much. I depend on auditjs a lot for finding the vulnerabilities in js. Appreciate you guys maintaining the oss index vul db.
